### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.OnSettingsChanged`1
  commentId: T:Vintagestory.API.Client.OnSettingsChanged`1
  id: OnSettingsChanged`1
  parent: Vintagestory.API.Client
  children: []
  langs:
  - csharp
  - vb
  name: OnSettingsChanged<T>
  nameWithType: OnSettingsChanged<T>
  fullName: Vintagestory.API.Client.OnSettingsChanged<T>
  type: Delegate
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: OnSettingsChanged
    path: Client/API/ISettings.cs
    startLine: 4
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: public delegate void OnSettingsChanged<T>(T newValue)
    parameters:
    - id: newValue
      type: '{T}'
    typeParameters:
    - id: T
    content.vb: Public Delegate Sub OnSettingsChanged(Of T)(newValue As T)
  nameWithType.vb: OnSettingsChanged(Of T)
  fullName.vb: Vintagestory.API.Client.OnSettingsChanged(Of T)
  name.vb: OnSettingsChanged(Of T)
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
