### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.ISettingsClass`1
  commentId: T:Vintagestory.API.Client.ISettingsClass`1
  id: ISettingsClass`1
  parent: Vintagestory.API.Client
  children:
  - Vintagestory.API.Client.ISettingsClass`1.AddWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  - Vintagestory.API.Client.ISettingsClass`1.Exists(System.String)
  - Vintagestory.API.Client.ISettingsClass`1.Get(System.String,`0)
  - Vintagestory.API.Client.ISettingsClass`1.Item(System.String)
  - Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  langs:
  - csharp
  - vb
  name: ISettingsClass<T>
  nameWithType: ISettingsClass<T>
  fullName: Vintagestory.API.Client.ISettingsClass<T>
  type: Interface
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: ISettingsClass
    path: Client/API/ISettings.cs
    startLine: 10
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Setting interface.
  example: []
  syntax:
    content: public interface ISettingsClass<T>
    typeParameters:
    - id: T
      description: The type of the given setting.
    content.vb: Public Interface ISettingsClass(Of T)
  nameWithType.vb: ISettingsClass(Of T)
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T)
  name.vb: ISettingsClass(Of T)
- uid: Vintagestory.API.Client.ISettingsClass`1.Item(System.String)
  commentId: P:Vintagestory.API.Client.ISettingsClass`1.Item(System.String)
  id: Item(System.String)
  parent: Vintagestory.API.Client.ISettingsClass`1
  langs:
  - csharp
  - vb
  name: this[string]
  nameWithType: ISettingsClass<T>.this[string]
  fullName: Vintagestory.API.Client.ISettingsClass<T>.this[string]
  type: Property
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: this[]
    path: Client/API/ISettings.cs
    startLine: 17
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Gets and sets the setting with the provided key.
  example: []
  syntax:
    content: T this[string key] { get; set; }
    parameters:
    - id: key
      type: System.String
      description: The key to the setting.
    return:
      type: '{T}'
      description: The current value of the given key.
    content.vb: Default Property this[](key As String) As T
  overload: Vintagestory.API.Client.ISettingsClass`1.Item*
  nameWithType.vb: ISettingsClass(Of T).this[](String)
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).this[](String)
  name.vb: this[](String)
- uid: Vintagestory.API.Client.ISettingsClass`1.Get(System.String,`0)
  commentId: M:Vintagestory.API.Client.ISettingsClass`1.Get(System.String,`0)
  id: Get(System.String,`0)
  parent: Vintagestory.API.Client.ISettingsClass`1
  langs:
  - csharp
  - vb
  name: Get(string, T)
  nameWithType: ISettingsClass<T>.Get(string, T)
  fullName: Vintagestory.API.Client.ISettingsClass<T>.Get(string, T)
  type: Method
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: Get
    path: Client/API/ISettings.cs
    startLine: 25
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Gets the setting with the provided key
  example: []
  syntax:
    content: T Get(string key, T defaultValue = default)
    parameters:
    - id: key
      type: System.String
      description: ''
    - id: defaultValue
      type: '{T}'
      description: ''
    return:
      type: '{T}'
      description: ''
    content.vb: Function [Get](key As String, defaultValue As T = Nothing) As T
  overload: Vintagestory.API.Client.ISettingsClass`1.Get*
  nameWithType.vb: ISettingsClass(Of T).Get(String, T)
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).Get(String, T)
  name.vb: Get(String, T)
- uid: Vintagestory.API.Client.ISettingsClass`1.Exists(System.String)
  commentId: M:Vintagestory.API.Client.ISettingsClass`1.Exists(System.String)
  id: Exists(System.String)
  parent: Vintagestory.API.Client.ISettingsClass`1
  langs:
  - csharp
  - vb
  name: Exists(string)
  nameWithType: ISettingsClass<T>.Exists(string)
  fullName: Vintagestory.API.Client.ISettingsClass<T>.Exists(string)
  type: Method
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: Exists
    path: Client/API/ISettings.cs
    startLine: 32
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Does this setting exist?
  example: []
  syntax:
    content: bool Exists(string key)
    parameters:
    - id: key
      type: System.String
      description: The key to check on a setting.
    return:
      type: System.Boolean
      description: Whether the setting exists or not.
    content.vb: Function Exists(key As String) As Boolean
  overload: Vintagestory.API.Client.ISettingsClass`1.Exists*
  nameWithType.vb: ISettingsClass(Of T).Exists(String)
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).Exists(String)
  name.vb: Exists(String)
- uid: Vintagestory.API.Client.ISettingsClass`1.AddWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  commentId: M:Vintagestory.API.Client.ISettingsClass`1.AddWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  id: AddWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  parent: Vintagestory.API.Client.ISettingsClass`1
  langs:
  - csharp
  - vb
  name: AddWatcher(string, OnSettingsChanged<T>)
  nameWithType: ISettingsClass<T>.AddWatcher(string, OnSettingsChanged<T>)
  fullName: Vintagestory.API.Client.ISettingsClass<T>.AddWatcher(string, Vintagestory.API.Client.OnSettingsChanged<T>)
  type: Method
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: AddWatcher
    path: Client/API/ISettings.cs
    startLine: 39
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Setting watcher for changes in values for a given setting.
  example: []
  syntax:
    content: void AddWatcher(string key, OnSettingsChanged<T> OnValueChanged)
    parameters:
    - id: key
      type: System.String
      description: Key to the setting
    - id: OnValueChanged
      type: Vintagestory.API.Client.OnSettingsChanged{{T}}
      description: the OnValueChanged event fired.
    content.vb: Sub AddWatcher(key As String, OnValueChanged As OnSettingsChanged(Of T))
  overload: Vintagestory.API.Client.ISettingsClass`1.AddWatcher*
  nameWithType.vb: ISettingsClass(Of T).AddWatcher(String, OnSettingsChanged(Of T))
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).AddWatcher(String, Vintagestory.API.Client.OnSettingsChanged(Of T))
  name.vb: AddWatcher(String, OnSettingsChanged(Of T))
- uid: Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  commentId: M:Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  id: RemoveWatcher(System.String,Vintagestory.API.Client.OnSettingsChanged{`0})
  parent: Vintagestory.API.Client.ISettingsClass`1
  langs:
  - csharp
  - vb
  name: RemoveWatcher(string, OnSettingsChanged<T>)
  nameWithType: ISettingsClass<T>.RemoveWatcher(string, OnSettingsChanged<T>)
  fullName: Vintagestory.API.Client.ISettingsClass<T>.RemoveWatcher(string, Vintagestory.API.Client.OnSettingsChanged<T>)
  type: Method
  source:
    remote:
      path: VintagestoryApi/Client/API/ISettings.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: RemoveWatcher
    path: Client/API/ISettings.cs
    startLine: 47
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Removes a previously assigned watcher
  example: []
  syntax:
    content: bool RemoveWatcher(string key, OnSettingsChanged<T> handler)
    parameters:
    - id: key
      type: System.String
      description: ''
    - id: handler
      type: Vintagestory.API.Client.OnSettingsChanged{{T}}
      description: ''
    return:
      type: System.Boolean
      description: True if successfully removed
    content.vb: Function RemoveWatcher(key As String, handler As OnSettingsChanged(Of T)) As Boolean
  overload: Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher*
  nameWithType.vb: ISettingsClass(Of T).RemoveWatcher(String, OnSettingsChanged(Of T))
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).RemoveWatcher(String, Vintagestory.API.Client.OnSettingsChanged(Of T))
  name.vb: RemoveWatcher(String, OnSettingsChanged(Of T))
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: Vintagestory.API.Client.ISettingsClass`1.Item*
  commentId: Overload:Vintagestory.API.Client.ISettingsClass`1.Item
  href: Vintagestory.API.Client.ISettingsClass-1.html#Vintagestory_API_Client_ISettingsClass_1_Item_System_String_
  name: this
  nameWithType: ISettingsClass<T>.this
  fullName: Vintagestory.API.Client.ISettingsClass<T>.this
  nameWithType.vb: ISettingsClass(Of T).this[]
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).this[]
  name.vb: this[]
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: Vintagestory.API.Client.ISettingsClass`1.Get*
  commentId: Overload:Vintagestory.API.Client.ISettingsClass`1.Get
  href: Vintagestory.API.Client.ISettingsClass-1.html#Vintagestory_API_Client_ISettingsClass_1_Get_System_String__0_
  name: Get
  nameWithType: ISettingsClass<T>.Get
  fullName: Vintagestory.API.Client.ISettingsClass<T>.Get
  nameWithType.vb: ISettingsClass(Of T).Get
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).Get
- uid: Vintagestory.API.Client.ISettingsClass`1.Exists*
  commentId: Overload:Vintagestory.API.Client.ISettingsClass`1.Exists
  href: Vintagestory.API.Client.ISettingsClass-1.html#Vintagestory_API_Client_ISettingsClass_1_Exists_System_String_
  name: Exists
  nameWithType: ISettingsClass<T>.Exists
  fullName: Vintagestory.API.Client.ISettingsClass<T>.Exists
  nameWithType.vb: ISettingsClass(Of T).Exists
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).Exists
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Vintagestory.API.Client.ISettingsClass`1.AddWatcher*
  commentId: Overload:Vintagestory.API.Client.ISettingsClass`1.AddWatcher
  href: Vintagestory.API.Client.ISettingsClass-1.html#Vintagestory_API_Client_ISettingsClass_1_AddWatcher_System_String_Vintagestory_API_Client_OnSettingsChanged__0__
  name: AddWatcher
  nameWithType: ISettingsClass<T>.AddWatcher
  fullName: Vintagestory.API.Client.ISettingsClass<T>.AddWatcher
  nameWithType.vb: ISettingsClass(Of T).AddWatcher
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).AddWatcher
- uid: Vintagestory.API.Client.OnSettingsChanged{{T}}
  commentId: T:Vintagestory.API.Client.OnSettingsChanged{`0}
  parent: Vintagestory.API.Client
  definition: Vintagestory.API.Client.OnSettingsChanged`1
  href: Vintagestory.API.Client.OnSettingsChanged-1.html
  name: OnSettingsChanged<T>
  nameWithType: OnSettingsChanged<T>
  fullName: Vintagestory.API.Client.OnSettingsChanged<T>
  nameWithType.vb: OnSettingsChanged(Of T)
  fullName.vb: Vintagestory.API.Client.OnSettingsChanged(Of T)
  name.vb: OnSettingsChanged(Of T)
  spec.csharp:
  - uid: Vintagestory.API.Client.OnSettingsChanged`1
    name: OnSettingsChanged
    href: Vintagestory.API.Client.OnSettingsChanged-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Vintagestory.API.Client.OnSettingsChanged`1
    name: OnSettingsChanged
    href: Vintagestory.API.Client.OnSettingsChanged-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Vintagestory.API.Client.OnSettingsChanged`1
  commentId: T:Vintagestory.API.Client.OnSettingsChanged`1
  href: Vintagestory.API.Client.OnSettingsChanged-1.html
  name: OnSettingsChanged<T>
  nameWithType: OnSettingsChanged<T>
  fullName: Vintagestory.API.Client.OnSettingsChanged<T>
  nameWithType.vb: OnSettingsChanged(Of T)
  fullName.vb: Vintagestory.API.Client.OnSettingsChanged(Of T)
  name.vb: OnSettingsChanged(Of T)
  spec.csharp:
  - uid: Vintagestory.API.Client.OnSettingsChanged`1
    name: OnSettingsChanged
    href: Vintagestory.API.Client.OnSettingsChanged-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Vintagestory.API.Client.OnSettingsChanged`1
    name: OnSettingsChanged
    href: Vintagestory.API.Client.OnSettingsChanged-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher*
  commentId: Overload:Vintagestory.API.Client.ISettingsClass`1.RemoveWatcher
  href: Vintagestory.API.Client.ISettingsClass-1.html#Vintagestory_API_Client_ISettingsClass_1_RemoveWatcher_System_String_Vintagestory_API_Client_OnSettingsChanged__0__
  name: RemoveWatcher
  nameWithType: ISettingsClass<T>.RemoveWatcher
  fullName: Vintagestory.API.Client.ISettingsClass<T>.RemoveWatcher
  nameWithType.vb: ISettingsClass(Of T).RemoveWatcher
  fullName.vb: Vintagestory.API.Client.ISettingsClass(Of T).RemoveWatcher
