### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.OnValueSetDelegate
  commentId: T:Vintagestory.API.Client.OnValueSetDelegate
  id: OnValueSetDelegate
  parent: Vintagestory.API.Client
  children: []
  langs:
  - csharp
  - vb
  name: OnValueSetDelegate
  nameWithType: OnValueSetDelegate
  fullName: Vintagestory.API.Client.OnValueSetDelegate
  type: Delegate
  source:
    remote:
      path: VintagestoryApi/Client/UI/JsonDialog.cs
      branch: b694fee1bf3e4ebb962b650b962504ea17bce166
      repo: https://gitlab-ci-token:64_nSEkar94LMeYjNTUoKdg@git.striver.net/vintagecraft/game.git
    id: OnValueSetDelegate
    path: Client/UI/JsonDialog.cs
    startLine: 5
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: public delegate void OnValueSetDelegate(string elementCode, string newValue)
    parameters:
    - id: elementCode
      type: System.String
    - id: newValue
      type: System.String
    content.vb: Public Delegate Sub OnValueSetDelegate(elementCode As String, newValue As String)
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
