### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.IGuiComposerManager
  commentId: T:Vintagestory.API.Client.IGuiComposerManager
  id: IGuiComposerManager
  parent: Vintagestory.API.Client
  children:
  - Vintagestory.API.Client.IGuiComposerManager.Composers
  - Vintagestory.API.Client.IGuiComposerManager.UnfocusElements
  langs:
  - csharp
  - vb
  name: IGuiComposerManager
  nameWithType: IGuiComposerManager
  fullName: Vintagestory.API.Client.IGuiComposerManager
  type: Interface
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: public interface IGuiComposerManager
    content.vb: Public Interface IGuiComposerManager
- uid: Vintagestory.API.Client.IGuiComposerManager.UnfocusElements
  commentId: M:Vintagestory.API.Client.IGuiComposerManager.UnfocusElements
  id: UnfocusElements
  parent: Vintagestory.API.Client.IGuiComposerManager
  langs:
  - csharp
  - vb
  name: UnfocusElements()
  nameWithType: IGuiComposerManager.UnfocusElements()
  fullName: Vintagestory.API.Client.IGuiComposerManager.UnfocusElements()
  type: Method
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: void UnfocusElements()
    content.vb: Sub UnfocusElements()
  overload: Vintagestory.API.Client.IGuiComposerManager.UnfocusElements*
- uid: Vintagestory.API.Client.IGuiComposerManager.Composers
  commentId: P:Vintagestory.API.Client.IGuiComposerManager.Composers
  id: Composers
  parent: Vintagestory.API.Client.IGuiComposerManager
  langs:
  - csharp
  - vb
  name: Composers
  nameWithType: IGuiComposerManager.Composers
  fullName: Vintagestory.API.Client.IGuiComposerManager.Composers
  type: Property
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: Dictionary<string, GuiComposer> Composers { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,Vintagestory.API.Client.GuiComposer}
    content.vb: ReadOnly Property Composers As Dictionary(Of String, GuiComposer)
  overload: Vintagestory.API.Client.IGuiComposerManager.Composers*
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: Vintagestory.API.Client.IGuiComposerManager.UnfocusElements*
  commentId: Overload:Vintagestory.API.Client.IGuiComposerManager.UnfocusElements
  href: Vintagestory.API.Client.IGuiComposerManager.html#Vintagestory_API_Client_IGuiComposerManager_UnfocusElements
  name: UnfocusElements
  nameWithType: IGuiComposerManager.UnfocusElements
  fullName: Vintagestory.API.Client.IGuiComposerManager.UnfocusElements
- uid: Vintagestory.API.Client.IGuiComposerManager.Composers*
  commentId: Overload:Vintagestory.API.Client.IGuiComposerManager.Composers
  href: Vintagestory.API.Client.IGuiComposerManager.html#Vintagestory_API_Client_IGuiComposerManager_Composers
  name: Composers
  nameWithType: IGuiComposerManager.Composers
  fullName: Vintagestory.API.Client.IGuiComposerManager.Composers
- uid: System.Collections.Generic.Dictionary{System.String,Vintagestory.API.Client.GuiComposer}
  commentId: T:System.Collections.Generic.Dictionary{System.String,Vintagestory.API.Client.GuiComposer}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, GuiComposer>
  nameWithType: Dictionary<string, GuiComposer>
  fullName: System.Collections.Generic.Dictionary<string, Vintagestory.API.Client.GuiComposer>
  nameWithType.vb: Dictionary(Of String, GuiComposer)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, Vintagestory.API.Client.GuiComposer)
  name.vb: Dictionary(Of String, GuiComposer)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Vintagestory.API.Client.GuiComposer
    name: GuiComposer
    href: Vintagestory.API.Client.GuiComposer.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: Vintagestory.API.Client.GuiComposer
    name: GuiComposer
    href: Vintagestory.API.Client.GuiComposer.html
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
