### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.ConfigItemClickDelegate
  commentId: T:Vintagestory.API.Client.ConfigItemClickDelegate
  id: ConfigItemClickDelegate
  parent: Vintagestory.API.Client
  children: []
  langs:
  - csharp
  - vb
  name: ConfigItemClickDelegate
  nameWithType: ConfigItemClickDelegate
  fullName: Vintagestory.API.Client.ConfigItemClickDelegate
  type: Delegate
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: ConfigItemClickDelegate
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 57
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: public delegate void ConfigItemClickDelegate(int index, int indexWithoutTitles)
    parameters:
    - id: index
      type: System.Int32
    - id: indexWithoutTitles
      type: System.Int32
    content.vb: Public Delegate Sub ConfigItemClickDelegate(index As Integer, indexWithoutTitles As Integer)
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
