### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Config.OS
  commentId: T:Vintagestory.API.Config.OS
  id: OS
  parent: Vintagestory.API.Config
  children:
  - Vintagestory.API.Config.OS.Linux
  - Vintagestory.API.Config.OS.Mac
  - Vintagestory.API.Config.OS.Windows
  langs:
  - csharp
  - vb
  name: OS
  nameWithType: OS
  fullName: Vintagestory.API.Config.OS
  type: Enum
  source:
    remote:
      path: VintagestoryApi/Config/RuntimeEnv.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: OS
    path: Config/RuntimeEnv.cs
    startLine: 14
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  summary: Operating System Enum
  example: []
  syntax:
    content: public enum OS
    content.vb: Public Enum OS
- uid: Vintagestory.API.Config.OS.Windows
  commentId: F:Vintagestory.API.Config.OS.Windows
  id: Windows
  parent: Vintagestory.API.Config.OS
  langs:
  - csharp
  - vb
  name: Windows
  nameWithType: OS.Windows
  fullName: Vintagestory.API.Config.OS.Windows
  type: Field
  source:
    remote:
      path: VintagestoryApi/Config/RuntimeEnv.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: Windows
    path: Config/RuntimeEnv.cs
    startLine: 16
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Windows = 0
    return:
      type: Vintagestory.API.Config.OS
- uid: Vintagestory.API.Config.OS.Mac
  commentId: F:Vintagestory.API.Config.OS.Mac
  id: Mac
  parent: Vintagestory.API.Config.OS
  langs:
  - csharp
  - vb
  name: Mac
  nameWithType: OS.Mac
  fullName: Vintagestory.API.Config.OS.Mac
  type: Field
  source:
    remote:
      path: VintagestoryApi/Config/RuntimeEnv.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: Mac
    path: Config/RuntimeEnv.cs
    startLine: 17
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Mac = 1
    return:
      type: Vintagestory.API.Config.OS
- uid: Vintagestory.API.Config.OS.Linux
  commentId: F:Vintagestory.API.Config.OS.Linux
  id: Linux
  parent: Vintagestory.API.Config.OS
  langs:
  - csharp
  - vb
  name: Linux
  nameWithType: OS.Linux
  fullName: Vintagestory.API.Config.OS.Linux
  type: Field
  source:
    remote:
      path: VintagestoryApi/Config/RuntimeEnv.cs
      branch: f42a12683a5672fcf06b1bea827a0110728d0177
      repo: https://gitlab-ci-token:64_g25Wum55R8kbboPMqahT@git.striver.net/vintagecraft/game.git
    id: Linux
    path: Config/RuntimeEnv.cs
    startLine: 18
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Linux = 2
    return:
      type: Vintagestory.API.Config.OS
references:
- uid: Vintagestory.API.Config
  commentId: N:Vintagestory.API.Config
  href: Vintagestory.html
  name: Vintagestory.API.Config
  nameWithType: Vintagestory.API.Config
  fullName: Vintagestory.API.Config
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
- uid: Vintagestory.API.Config.OS
  commentId: T:Vintagestory.API.Config.OS
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.OS.html
  name: OS
  nameWithType: OS
  fullName: Vintagestory.API.Config.OS
