### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Config.EnumReleaseType
  commentId: T:Vintagestory.API.Config.EnumReleaseType
  id: EnumReleaseType
  parent: Vintagestory.API.Config
  children:
  - Vintagestory.API.Config.EnumReleaseType.Candidate
  - Vintagestory.API.Config.EnumReleaseType.Development
  - Vintagestory.API.Config.EnumReleaseType.Preview
  - Vintagestory.API.Config.EnumReleaseType.Stable
  langs:
  - csharp
  - vb
  name: EnumReleaseType
  nameWithType: EnumReleaseType
  fullName: Vintagestory.API.Config.EnumReleaseType
  type: Enum
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: public enum EnumReleaseType
    content.vb: Public Enum EnumReleaseType
- uid: Vintagestory.API.Config.EnumReleaseType.Stable
  commentId: F:Vintagestory.API.Config.EnumReleaseType.Stable
  id: Stable
  parent: Vintagestory.API.Config.EnumReleaseType
  langs:
  - csharp
  - vb
  name: Stable
  nameWithType: EnumReleaseType.Stable
  fullName: Vintagestory.API.Config.EnumReleaseType.Stable
  type: Field
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Stable = 0
    return:
      type: Vintagestory.API.Config.EnumReleaseType
- uid: Vintagestory.API.Config.EnumReleaseType.Candidate
  commentId: F:Vintagestory.API.Config.EnumReleaseType.Candidate
  id: Candidate
  parent: Vintagestory.API.Config.EnumReleaseType
  langs:
  - csharp
  - vb
  name: Candidate
  nameWithType: EnumReleaseType.Candidate
  fullName: Vintagestory.API.Config.EnumReleaseType.Candidate
  type: Field
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Candidate = 1
    return:
      type: Vintagestory.API.Config.EnumReleaseType
- uid: Vintagestory.API.Config.EnumReleaseType.Preview
  commentId: F:Vintagestory.API.Config.EnumReleaseType.Preview
  id: Preview
  parent: Vintagestory.API.Config.EnumReleaseType
  langs:
  - csharp
  - vb
  name: Preview
  nameWithType: EnumReleaseType.Preview
  fullName: Vintagestory.API.Config.EnumReleaseType.Preview
  type: Field
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Preview = 2
    return:
      type: Vintagestory.API.Config.EnumReleaseType
- uid: Vintagestory.API.Config.EnumReleaseType.Development
  commentId: F:Vintagestory.API.Config.EnumReleaseType.Development
  id: Development
  parent: Vintagestory.API.Config.EnumReleaseType
  langs:
  - csharp
  - vb
  name: Development
  nameWithType: EnumReleaseType.Development
  fullName: Vintagestory.API.Config.EnumReleaseType.Development
  type: Field
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Config
  syntax:
    content: Development = 3
    return:
      type: Vintagestory.API.Config.EnumReleaseType
references:
- uid: Vintagestory.API.Config
  commentId: N:Vintagestory.API.Config
  href: Vintagestory.html
  name: Vintagestory.API.Config
  nameWithType: Vintagestory.API.Config
  fullName: Vintagestory.API.Config
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Config
    name: Config
    href: Vintagestory.API.Config.html
- uid: Vintagestory.API.Config.EnumReleaseType
  commentId: T:Vintagestory.API.Config.EnumReleaseType
  parent: Vintagestory.API.Config
  href: Vintagestory.API.Config.EnumReleaseType.html
  name: EnumReleaseType
  nameWithType: EnumReleaseType
  fullName: Vintagestory.API.Config.EnumReleaseType
