name: build-docs

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

env:
  DOCFX_SOURCE_BRANCH_NAME: master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx.json

    - name: Commit changes
      run: | 
        git config user.name "github-actions [bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs
        git commit -m "docs: Build for ${GITHUB_SHA}"
        git push
