name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx.json

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: master
        FOLDER: ./docs/_site
